services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build: ./backend/backend
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=SignAppDb;User Id=sa;Password=YourStrong!Password;TrustServerCertificate=true
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend

volumes:
  mssql_data:
